import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:islamic_app/model/suraModel.dart';
import 'package:islamic_app/myProviders/myProvider.dart';
import 'package:islamic_app/myThemeData.dart';
import 'package:islamic_app/screens/suraScreen.dart';
import 'package:provider/provider.dart';

// ignore: must_be_immutable
class Quranscreen extends StatelessWidget {
  List<Map<String, String>> surasNameEn = [
    {"Al-Fatihah": "7"},
    {"Al-Baqarah": "286"},
    {"Aal-E-Imran": "200"},
    {"An-Nisa'": "176"},
    {"Al-Ma'idah": "120"},
    {"Al-An'am": "165"},
    {"Al-A'raf": "206"},
    {"Al-Anfal": "75"},
    {"At-Tawbah": "129"},
    {"Yunus": "109"},
    {"Hud": "123"},
    {"Yusuf": "111"},
    {"Ar-Ra'd": "43"},
    {"Ibrahim": "52"},
    {"Al-Hijr": "99"},
    {"An-Nahl": "128"},
    {"Al-Isra'": "111"},
    {"Al-Kahf": "110"},
    {"Maryam": "98"},
    {"Ta-Ha": "135"},
    {"Al-Anbiya'": "112"},
    {"Al-Hajj": "78"},
    {"Al-Mu'minun": "118"},
    {"An-Nur": "64"},
    {"Al-Furqan": "77"},
    {"Ash-Shu'ara'": "227"},
    {"An-Naml": "93"},
    {"Al-Qasas": "88"},
    {"Al-Ankabut": "69"},
    {"Ar-Rum": "60"},
    {"Luqman": "34"},
    {"As-Sajda": "30"},
    {"Al-Ahzab": "73"},
    {"Saba": "54"},
    {"Fatir": "45"},
    {"Ya-Sin": "83"},
    {"As-Saffat": "182"},
    {"Sad": "88"},
    {"Az-Zumar": "75"},
    {"Ghafir": "85"},
    {"Fussilat": "54"},
    {"Ash-Shura": "53"},
    {"Az-Zukhruf": "89"},
    {"Ad-Dukhan": "59"},
    {"Al-Jathiya": "37"},
    {"Al-Ahqaf": "35"},
    {"Muhammad": "38"},
    {"Al-Fath": "29"},
    {"Al-Hujurat": "18"},
    {"Qaf": "45"},
    {"Adh-Dhariyat": "60"},
    {"At-Tur": "49"},
    {"An-Najm": "62"},
    {"Al-Qamar": "55"},
    {"Ar-Rahman": "78"},
    {"Al-Waqi'a": "96"},
    {"Al-Hadid": "29"},
    {"Al-Mujadila": "22"},
    {"Al-Hashr": "24"},
    {"Al-Mumtahina": "13"},
    {"As-Saff": "14"},
    {"Al-Jumu'a": "11"},
    {"Al-Munafiqun": "11"},
    {"At-Taghabun": "18"},
    {"At-Talaq": "12"},
    {"At-Tahrim": "12"},
    {"Al-Mulk": "30"},
    {"Al-Qalam": "52"},
    {"Al-Haqqah": "52"},
    {"Al-Ma'arij": "44"},
    {"Nuh": "28"},
    {"Al-Jinn": "28"},
    {"Al-Muzzammil": "20"},
    {"Al-Muddathir": "56"},
    {"Al-Qiyamah": "40"},
    {"Al-Insan": "31"},
    {"Al-Mursalat": "50"},
    {"An-Naba'": "40"},
    {"An-Nazi'at": "46"},
    {"Abasa": "42"},
    {"At-Takwir": "29"},
    {"Al-Infitar": "19"},
    {"Al-Mutaffifin": "36"},
    {"Al-Inshiqaq": "25"},
    {"Al-Buruj": "22"},
    {"At-Tariq": "17"},
    {"Al-Ala": "19"},
    {"Al-Ghashiyah": "26"},
    {"Al-Fajr": "30"},
    {"Al-Balad": "20"},
    {"Ash-Shams": "15"},
    {"Al-Lail": "21"},
    {"Ad-Duha": "11"},
    {"Ash-Sharh": "8"},
    {"At-Tin": "8"},
    {"Al-Alaq": "19"},
    {"Al-Qadr": "5"},
    {"Al-Bayyina": "8"},
    {"Az-Zalzalah": "8"},
    {"Al-Adiyat": "11"},
    {"Al-Qari'a": "11"},
    {"At-Takathur": "8"},
    {"Al-Asr": "3"},
    {"Al-Humazah": "9"},
    {"Al-Fil": "5"},
    {"Quraish": "4"},
    {"Al-Ma'un": "7"},
    {"Al-Kawthar": "3"},
    {"Al-Kafirun": "6"},
    {"An-Nasr": "3"},
    {"Al-Masad": "5"},
    {"Al-Ikhlas": "4"},
    {"Al-Falaq": "5"},
    {"An-Nas": "6"},
  ];

  List<Map<String, String>> surasNameAr = [
    {"الفاتحه": "7"},
    {"البقرة": "286"},
    {"آل عمران": "200"},
    {"النساء": "176"},
    {"المائدة": "120"},
    {"الأنعام": "165"},
    {"الأعراف": "206"},
    {"الأنفال": "75"},
    {"التوبة": "129"},
    {"يونس": "109"},
    {"هود": "123"},
    {"يوسف": "111"},
    {"الرعد": "43"},
    {"إبراهيم": "52"},
    {"الحجر": "99"},
    {"النحل": "128"},
    {"الإسراء": "111"},
    {"الكهف": "110"},
    {"مريم": "98"},
    {"طه": "135"},
    {"الأنبياء": "112"},
    {"الحج": "78"},
    {"المؤمنون": "118"},
    {"النّور": "64"},
    {"الفرقان": "77"},
    {"الشعراء": "227"},
    {"النّمل": "93"},
    {"القصص": "88"},
    {"العنكبوت": "69"},
    {"الرّوم": "60"},
    {"لقمان": "34"},
    {"السجدة": "30"},
    {"الأحزاب": "73"},
    {"سبأ": "54"},
    {"فاطر": "45"},
    {"يس": "83"},
    {"الصافات": "182"},
    {"ص": "88"},
    {"الزمر": "75"},
    {"غافر": "85"},
    {"فصّلت": "54"},
    {"الشورى": "53"},
    {"الزخرف": "89"},
    {"الدّخان": "59"},
    {"الجاثية": "37"},
    {"الأحقاف": "35"},
    {"محمد": "38"},
    {"الفتح": "29"},
    {"الحجرات": "18"},
    {"ق": "45"},
    {"الذاريات": "60"},
    {"الطور": "49"},
    {"النجم": "62"},
    {"القمر": "55"},
    {"الرحمن": "78"},
    {"الواقعة": "96"},
    {"الحديد": "29"},
    {"المجادلة": "22"},
    {"الحشر": "24"},
    {"الممتحنة": "13"},
    {"الصف": "14"},
    {"الجمعة": "11"},
    {"المنافقون": "11"},
    {"التغابن": "18"},
    {"الطلاق": "12"},
    {"التحريم": "12"},
    {"الملك": "30"},
    {"القلم": "52"},
    {"الحاقة": "52"},
    {"المعارج": "44"},
    {"نوح": "28"},
    {"الجن": "28"},
    {"المزّمّل": "20"},
    {"المدّثر": "56"},
    {"القيامة": "40"},
    {"الإنسان": "31"},
    {"المرسلات": "50"},
    {"النبأ": "40"},
    {"النازعات": "46"},
    {"عبس": "42"},
    {"التكوير": "29"},
    {"الإنفطار": "19"},
    {"المطفّفين": "36"},
    {"الإنشقاق": "25"},
    {"البروج": "22"},
    {"الطارق": "17"},
    {"الأعلى": "19"},
    {"الغاشية": "26"},
    {"الفجر": "30"},
    {"البلد": "20"},
    {"الشمس": "15"},
    {"الليل": "21"},
    {"الضحى": "11"},
    {"الشرح": "8"},
    {"التين": "8"},
    {"العلق": "19"},
    {"القدر": "5"},
    {"البينة": "8"},
    {"الزلزلة": "8"},
    {"العاديات": "11"},
    {"القارعة": "11"},
    {"التكاثر": "8"},
    {"العصر": "3"},
    {"الهمزة": "9"},
    {"الفيل": "5"},
    {"قريش": "4"},
    {"الماعون": "7"},
    {"الكوثر": "3"},
    {"الكافرون": "6"},
    {"النصر": "3"},
    {"المسد": "5"},
    {"الإخلاص": "4"},
    {"الفلق": "5"},
    {"الناس": "6"},
  ];

  @override
  Widget build(BuildContext context) {
    var provider = Provider.of<MyProvider>(context);
    return Center(
      child: Column(
        children: [
          Image.asset("assets/images/qur2an_screen_logo.png"),
          Table(
            border: TableBorder(
                top: BorderSide(
                  width: 3,
                  color: provider.isDark
                      ? MyThemeData.DarkprimaryColor
                      : MyThemeData.primaryColor,
                ),
                bottom: BorderSide(
                  width: 3,
                  color: provider.isDark
                      ? MyThemeData.DarkprimaryColor
                      : MyThemeData.primaryColor,
                ),
                verticalInside: BorderSide(
                  width: 3,
                  color: provider.isDark
                      ? MyThemeData.DarkprimaryColor
                      : MyThemeData.primaryColor,
                )),
            children: [
              TableRow(children: [
                Padding(
                  padding: const EdgeInsets.symmetric(vertical: 5.0),
                  child: Text(
                    "sName".tr(),
                    style: Theme.of(context).textTheme.bodyLarge,
                    textAlign: TextAlign.center,
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.symmetric(vertical: 5.0),
                  child: Text(
                    "versesNumbers".tr(),
                    style: Theme.of(context).textTheme.bodyLarge,
                    textAlign: TextAlign.center,
                  ),
                ),
              ]),
            ],
          ),
          Expanded(
            child: ListView.builder(
              itemCount: surasNameAr.length,
              itemBuilder: (context, index) {
                return InkWell(
                  onTap: () {
                    Navigator.pushNamed(context, SureScreen.RouteName,
                        arguments: SuraModel(
                            SuraName: surasNameAr[index].keys.first,
                            index: index));
                  },
                  child: Table(
                    border: TableBorder.symmetric(
                      inside: BorderSide(
                        color: provider.isDark
                            ? MyThemeData.DarkprimaryColor
                            : MyThemeData.primaryColor,
                        width: 3,
                      ),
                    ),
                    children: [
                      TableRow(
                        children: [
                          Text(
                            provider.isEnglish
                                ? surasNameEn[index].keys.first
                                : surasNameAr[index].keys.first,
                            style: Theme.of(context).textTheme.bodyLarge,
                            textAlign: TextAlign.center,
                          ),
                          Padding(
                            padding: const EdgeInsets.symmetric(vertical: 5.0),
                            child: Text(
                              surasNameAr[index].values.first,
                              style: Theme.of(context).textTheme.bodyLarge,
                              textAlign: TextAlign.center,
                            ),
                          ),
                        ],
                      ),
                    ],
                  ),
                );
              },
            ),
          )
        ],
      ),
    );
  }
}
